### ISSUE TITLE
Not working in laravel 6

### ISSUE THREAD

**Issue by devlimon** [maddhatter/laravel-fullcalendar#152]
i used this package in one of my big systems that was built with laravel 5.6 and now i upgraded the systems to laravel 6 and now i am not able to install this package in laravel 6.

**Comment by Helidalto** [comment]
veja este link se te ajuda 
https://github.com/maddhatter/laravel-fullcalendar/issues/149

**Comment by devlimon** [comment]
Thanks for your reply.

I forked & updated according to instruction and also tried to install the updated package of @rayblair06. But not working.I am trying again.

**Comment by Helidalto** [comment]
Hello!
Do the following, check if there is the "repositories" tag in the composer.json file, if not add:
   "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/rayblair06/laravel-fullcalendar.git"
        }
    ],

and finally add require "maddhatter / laravel-fullcalendar": "^ 1.3"

done this execute "composer update"

for me it worked, I hope I helped, big hug!

**Comment by adriancampanaro** [comment]
Can someone provide the fullsteps to get this working in v6 as I still cannot get it working

**Comment by Twelvefat** [comment]
> Hello!
> Do the following, check if there is the "repositories" tag in the composer.json file, if not add:
> "repositories": [
> {
> "type": "vcs",
> "url": "https://github.com/rayblair06/laravel-fullcalendar.git"
> }
> ],
> 
> and finally add require "maddhatter / laravel-fullcalendar": "^ 1.3"
> 
> done this execute "composer update"
> 
> for me it worked, I hope I helped, big hug!


Thank you, its work for me ^^

**Comment by devlimon** [comment]
guys , don't use package for Event fullcalendar . why need to take pain of update ?  when laravel updates needed then package hampers.  my opinion is not use any package for small task. 

now,  i am using direct JavaScript plugin, and it's really simple :

https://fullcalendar.io/docs/getting-started

**Comment by takunda91** [comment]
> Hello!
> Do the following, check if there is the "repositories" tag in the composer.json file, if not add:
> "repositories": [
> {
> "type": "vcs",
> "url": "https://github.com/rayblair06/laravel-fullcalendar.git"
> }
> ],
> 
> and finally add require "maddhatter / laravel-fullcalendar": "^ 1.3"
> 
> done this execute "composer update"
> 
> for me it worked, I hope I helped, big hug!

This worked well.....

**Comment by kaz-97** [comment]
@takunda91 can you advise me where you add require "maddhatter / laravel-fullcalendar": "^ 1.3"

I am new to laravel so struggling to understand where is being referred to. Thanks in advance.

**Comment by Helidalto** [comment]
Hello! add to the composer.json file in "require"

done this execute "composer update"

**Comment by kaz-97** [comment]
> Hello! add to the composer.json file in "require"
> 
> done this execute "composer update"

Thank you kindly for your swift reply, i have added to the "require" in composer.json.
As for "finally add require "maddhatter / laravel-fullcalendar": "^ 1.3" can you explain where i need to insert this. Thanks again.

**Comment by Helidalto** [comment]
on the command line prompt, in the same place where you run the command "php artisan serve" for the application to run, I hope I helped.

**Comment by kaz-97** [comment]
Thank you.. silly me! Unfortunately still failed to install package. I shall look at alertnatives for v7 of laravel.

**Comment by badirox** [comment]
> Hello!
> Do the following, check if there is the "repositories" tag in the composer.json file, if not add:
> "repositories": [
> {
> "type": "vcs",
> "url": "https://github.com/rayblair06/laravel-fullcalendar.git"
> }
> ],
> 
> and finally add require "maddhatter / laravel-fullcalendar": "^ 1.3"
> 
> done this execute "composer update"
> 
> for me it worked, I hope I helped, big hug!

**Comment by tasdendu** [comment]
> Hello! Do the following, check if there is the "repositories" tag in the composer.json file, if not add: "repositories": [ { "type": "vcs", "url": "https://github.com/rayblair06/laravel-fullcalendar.git" } ],
> 
> and finally add require "maddhatter / laravel-fullcalendar": "^ 1.3"
> 
> done this execute "composer update"
> 
> for me it worked, I hope I helped, big hug!

This was the solution. Thanks a lot.
